### ISSUE TITLE
undecleared identifier: 'fileOpener' in appevents.nim

### ISSUE THREAD

**Issue by silverhikari** [johnnovak/gridmonger#11]
OS: Linux
NIM version: 2.0.2
packages installed: koi, nim-binstreams, nim-glfw, nim-nanovg, nim-osdialog, nim-riff, semver.nim, with
gridmonger version: git master a89b6ed

error log:
```
/home/silver/aur-packages-git/gridmonger/src/gridmonger/src/appevents.nim(199, 33) Error: undeclared identifier: 'fileOpener'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 3): 'g_fileOpenerCh'
 (3, 5): 'fileNewer'
```

**Comment by nleseul** [comment]
Fwiw, it looks like you can get past this error by adding a `when defined(macosx):` block around `createThread(g_fileOpenerThr, fileOpener)`. (Since `fileOpener` is only defined when `macosx` is defined, at line 63.)

Still doesn't build for me due to linker errors, but at least it gets a bit further.

**Comment by johnnovak** [comment]
Things are in flux because I'm preparing for v1.2.0. Yes, it doesn't even build on Windows with current main, I know.

A proper Linux build will come later this year (and CI job, etc.)
