### ISSUE TITLE
The value of boolean 'lvl.cell.trail' must be either 0 or 1, actual value 10

### ISSUE THREAD

**Issue by tin-pham** [johnnovak/gridmonger#14]
![image](https://github.com/johnnovak/gridmonger/assets/20679090/f4ecd340-f755-4f9d-a2a9-001f9a9c4f60)
I can't open my map anymore, even the backup file. I can open example map.

I link the map file, since Github not support gmm upload: https://drive.google.com/file/d/1J0zOgRyQBjSNAC2AheFLakwcRyRXLZPw/view?usp=sharing

**Comment by johnnovak** [comment]
@tin-pham Thanks, I will look into it.

I've noticed a few such cases when you can end up with a corrupted map file. These will be all fixed in the next version. There's not much to do with the current version, unfortunately, other than trying to avoid the actions that result in a corrupted map (but you wouldn't know what those are...)

The changelog for the next release will give you some hints though what operations to avoid. But this could be something I haven't noticed before with the trail markers stuff. I'll investigate.

https://github.com/johnnovak/gridmonger/blob/master/CHANGELOG.md

**Comment by tin-pham** [comment]
> @tin-pham Thanks, I will look into it.
> 
> I've noticed a few such cases when you can end up with a corrupted map file. These will be all fixed in the next version. There's not much to do with the current version, unfortunately, other than trying to avoid the actions that result in a corrupted map (but you wouldn't know what those are...)
> 
> The changelog for the next release will give you some hints though what operations to avoid. But this specific problem you've run into could be something I haven't noticed yet with the trail markers stuff. I'll investigate.
> 
> https://github.com/johnnovak/gridmonger/blob/master/CHANGELOG.md

I looking forward to see what action occur that, now I gonna try to backup file as much as I can

**Comment by johnnovak** [comment]
Here's your fixed map @tin-pham.

It's almost impossible to say with certainty what corrupted it. Probably it was a memory corruption when you used the problematic operations listed in the changelog.

[Ultima IV - Quest of the Avatar.gmm.zip](https://github.com/user-attachments/files/16043075/Ultima.IV.-.Quest.of.the.Avatar.gmm.zip)

The new version will be more stable so have patience until it comes out (in 1-2 months, hopefully).

**Comment by johnnovak** [comment]
Hopefully non-issue in v1.2.0, so closing.
