### ISSUE TITLE
Enhancement request: Links should (try to) auto-select unique colors

### ISSUE THREAD

**Issue by peterb12** [johnnovak/gridmonger#15]
Right now, all links are the same color (defined as 'Link Marker' in the theme editor). In order to determine where a link goes, one follows it with G. 

One potential improvement would be to have links cycle through colors (if not connected to an existing link). This would allow the user to infer the destination of a link by noting the color (if it's on the same map).

Certainly not necessary, and it might not mesh well with the style model of the themes. But just a thought.

**Comment by johnnovak** [comment]
My main problem with this is that any auto-colouring could break the visual styles—I'd like avoid that if there's a way. I'd only do auto-colouring anything only as a last resort... which, in practice, is probably never because I'll find another way 😆

But ok, even if we had this, I don't think it would help much. You can't easily make visual connections between a bunch of random colours. Then, as you said, if the source and destination are in different levels, this cannot work.

Even if the two linked points are within the confined of a single level, there is zero guarantee to map is zoomed out enough to see both the source and destination at once.

What I _would_ consider doing, though, and I think that would be an improvement and a continuation of this idea of yours, is to optionally display an overlay that shows straight lines connecting the linked cells withing the same level. These straight lines could be auto-coloured (e.g., by cycling through a list of 4-5 predefined colours or something). You could toggle this overlay with some shortcut to see all lines, or optionally only for a single linked cell if there is one under the cursor.

So thanks, and leep these ideas coming because they might inspire me to do something slightly different down the road 😎

**Comment by johnnovak** [comment]
@peterb12 It's more or less implemented. The blueish lines show the linked cells, and these overlaid lines can be toggled in various ways, etc.

<img width="1467" alt="image" src="https://github.com/johnnovak/gridmonger/assets/698770/e21d0a82-2df8-42bd-b2d0-0b2774c2ccbe">

**Comment by johnnovak** [comment]
Coming in v1.2.0.

**Comment by johnnovak** [comment]
@peterb12 I've just got CI dev builds going for every commit in `master`. Only for macOS, currently. So if you want to check out this feature, it's available in the latest dev build:

https://github.com/johnnovak/gridmonger/actions/runs/9827033338

Scroll down to the bottom, and download the ZIP package in the "artifacts" section (need to be logged in to GitHub to see it).

Warning: If you re-save a map in the dev build, that will upgrade your map file to a more recent format and you won't be able to load it into the current stable version anymore. Otherwise, the dev builds are pretty stable and some beta-testing is always welcome 😏
