### ISSUE TITLE
turn in walk mode

### ISSUE THREAD

**Issue by ribrdb** [johnnovak/gridmonger#6]
There should be keybindings to turn in walkmode if you don't have a keypad.

**Comment by johnnovak** [comment]
Good point. Should be easy to add.

**Comment by ahem** [comment]
It would be sweet if there was an option to switch the left/right arrow keys to mean turn instead of strafe. In old CRPGs like Bards Tale or Might and Magic, this is how the arrow keys are used, and it is a bit jarring to switch from left meaning turn to left meaning strafe all the time while simultaneously playing and mapping.

**Comment by johnnovak** [comment]
@ahem I think you'r right. It should be a preferences option to use left/right as strafing or turning in walk mode. That should fix the "no keypad" issue too.

**Comment by johnnovak** [comment]
Coming in v1.2.0.
